USE DATABASE SALES_ANALYTICS_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE SALES_RAW
(
    ROW_ID INTEGER,
    ORDER_ID STRING,
    ORDER_DATE DATE,
    SHIP_DATE DATE,
    SHIP_MODE STRING,

    CUSTOMER_ID STRING,
    CUSTOMER_NAME STRING,
    SEGMENT STRING,

    COUNTRY STRING,
    CITY STRING,
    STATE STRING,
    POSTAL_CODE STRING,
    REGION STRING,

    PRODUCT_ID STRING,
    CATEGORY STRING,
    SUB_CATEGORY STRING,
    PRODUCT_NAME STRING,

    SALES NUMBER(10,2)
);