USE DATABASE SALES_ANALYTICS_DB;
USE SCHEMA MART;

CREATE OR REPLACE TABLE DIM_CUSTOMER AS
SELECT DISTINCT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT
FROM SALES_ANALYTICS_DB.STAGING.SALES_STAGE;

CREATE OR REPLACE TABLE DIM_PRODUCT AS
SELECT
    PRODUCT_ID,
    MIN(PRODUCT_NAME) AS PRODUCT_NAME,
    MIN(CATEGORY) AS CATEGORY,
    MIN(SUB_CATEGORY) AS SUB_CATEGORY
FROM SALES_ANALYTICS_DB.STAGING.SALES_STAGE
GROUP BY PRODUCT_ID;

CREATE OR REPLACE TABLE DIM_LOCATION AS
SELECT DISTINCT
    COUNTRY,
    CITY,
    STATE,
    POSTAL_CODE,
    REGION
FROM SALES_ANALYTICS_DB.STAGING.SALES_STAGE;

CREATE OR REPLACE TABLE DIM_DATE AS
SELECT DISTINCT
    ORDER_DATE,
    YEAR(ORDER_DATE) AS ORDER_YEAR,
    MONTH(ORDER_DATE) AS ORDER_MONTH,
    MONTHNAME(ORDER_DATE) AS MONTH_NAME,
    DAY(ORDER_DATE) AS DAY_NUMBER
FROM SALES_ANALYTICS_DB.STAGING.SALES_STAGE;